# Generated by Django 4.0.1 on 2022-01-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Стиль')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-published'], 'verbose_name': 'Картина', 'verbose_name_plural': 'Картины'},
        ),
        migrations.AlterField(
            model_name='picture',
            name='artist',
            field=models.TextField(blank=True, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='picture',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pictures.style', verbose_name='Стиль'),
        ),
    ]
