# Generated by Django 4.0.1 on 2022-01-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_style_alter_picture_options_alter_picture_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ['style'], 'verbose_name': 'Стиль', 'verbose_name_plural': 'Стили'},
        ),
        migrations.RenameField(
            model_name='style',
            old_name='name',
            new_name='style',
        ),
    ]
